#!/bin/sh
print_help_and_exit() {
	echo "Usage: ./utils/newpackage <pkg>
install new package to virtualenv."
	exit 1
}

# main()
if [ -z "$1" -o "$1" = "--help" ]; then
	print_help_and_exit
fi

mkdir -p ~/d/pip-cache
bin/pip install --download-cache=~/d/pip-cache "$@"
